import 'reflect-metadata';
import * as assert from 'assert';
import { JwtService } from '@nestjs/jwt';
import { NestFactory } from '@nestjs/core';
import { DataSource } from 'typeorm';
import { AppModule } from '../src/app.module';
import { User, UserRole, UserStatus } from '../src/user/entities/user.entity';
import { GuardProfile } from '../src/guard-profile/entities/guard-profile.entity';
import { GuardScreening, HistoryType, ReferenceStatus, ScreeningAddress, ScreeningConsent, ScreeningEvidence, ScreeningHistory, ScreeningReference, ScreeningStatus, VerificationState } from '../src/screening/entities/screening.entities';
import { EvidenceCategory } from '../src/screening/entities/screening.entities';
import { AuditLog } from '../src/audit-log/entities/audit-log.entity';
import { Job } from '../src/job/entities/job.entity';
import { JobApplication } from '../src/job-application/entities/job-application.entity';
import { CompanyGuard } from '../src/company-guard/entities/company-guard.entity';
import { Assignment } from '../src/assignment/entities/assignment.entity';
import { GuardDocument, GuardDocumentType } from '../src/compliance/entities/guard-document.entity';
import { Company } from '../src/company/entities/company.entity';

let passed=0;function pass(name:string){passed++;console.log(`PASS ${name}`)}
async function main(){
 const url=process.env.SCREENING_CERT_DATABASE_URL;if(!url)throw new Error('SCREENING_CERT_DATABASE_URL is required');const parsed=new URL(url);if(!['127.0.0.1','localhost'].includes(parsed.hostname))throw new Error('API test database must be local');
 process.env.DATABASE_URL=url;process.env.DATABASE_SSL='false';process.env.DATABASE_SYNCHRONIZE='false';process.env.NODE_ENV='test';process.env.JWT_SECRET='sec017b-local-certification-secret-not-production';process.env.EVIDENCE_STORAGE_ENDPOINT='http://127.0.0.1:9';process.env.EVIDENCE_STORAGE_REGION='test';process.env.EVIDENCE_STORAGE_BUCKET='test';process.env.EVIDENCE_STORAGE_ACCESS_KEY_ID='test';process.env.EVIDENCE_STORAGE_SECRET_ACCESS_KEY='test';
 const app=await NestFactory.create(AppModule,{logger:false});await app.listen(0,'127.0.0.1');const address=app.getHttpServer().address();if(!address||typeof address==='string')throw new Error('No test port');const base=`http://127.0.0.1:${address.port}`;const ds=app.get(DataSource);
 try{
  const users=ds.getRepository(User);const guards=ds.getRepository(GuardProfile);const guard1=await guards.findOneOrFail({where:{siaLicenseNumber:'7000000000000001'}});const guard2=await guards.findOneOrFail({where:{siaLicenseNumber:'7000000000000002'}});const companyUser=await users.findOneByOrFail({email:'company@sec017b.test'});
  const admin=await users.findOneBy({email:'admin@sec017b.test'})??await users.save(users.create({email:'admin@sec017b.test',passwordHash:'not-a-login-hash',role:UserRole.ADMIN,status:UserStatus.ACTIVE,isEmailVerified:true}));const client=await users.findOneBy({email:'client@sec017b.test'})??await users.save(users.create({email:'client@sec017b.test',passwordHash:'not-a-login-hash',role:UserRole.CLIENT_VIEWER,status:UserStatus.ACTIVE,isEmailVerified:true}));
  const screeningRepo=ds.getRepository(GuardScreening);const previous=await screeningRepo.findOne({where:{guard:{id:guard1.id}}});if(previous)await screeningRepo.remove(previous);const screening=await screeningRepo.save(screeningRepo.create({guard:guard1,status:ScreeningStatus.UNDER_REVIEW,screeningPeriodYears:5,legalFullName:guard1.fullName,dateOfBirth:'1990-01-01',nationality:'British',currentAddress:'Test address',identityVerification:VerificationState.VERIFIED,identityVerificationMethod:'test',identityVerifiedByUserId:admin.id,identityVerifiedAt:new Date(),siaLicenceType:'Security guarding',siaRegisterVerification:VerificationState.VERIFIED,siaVerifiedByUserId:admin.id,siaVerifiedAt:new Date(),rightToWorkCheckMethod:'test',rightToWorkCheckDate:'2026-01-01',rightToWorkVerification:VerificationState.VERIFIED,rightToWorkVerifiedByUserId:admin.id,rightToWorkVerifiedAt:new Date(),reviewedByUserId:admin.id,reviewedAt:new Date()}));
  const start=new Date();start.setUTCFullYear(start.getUTCFullYear()-5);const history=await ds.getRepository(ScreeningHistory).save({screening,type:HistoryType.EMPLOYMENT,startDate:start.toISOString().slice(0,10),endDate:null,isCurrent:true,organisation:'Test Employer',description:'Test-only continuous employment',verificationState:VerificationState.VERIFIED});
  await ds.getRepository(ScreeningAddress).save({screening,address:'Test address',startDate:start.toISOString().slice(0,10),endDate:null,isCurrent:true,verificationState:VerificationState.VERIFIED});
  await ds.getRepository(ScreeningReference).save({screening,history,organisation:'Test Employer',contactPerson:'Test Referee',relationship:'Manager',businessEmail:'referee@sec017b.test',status:ReferenceStatus.VERIFIED,sourceVerified:true,verificationMethod:'Test source check',verifiedByUserId:admin.id,verifiedAt:new Date()});
  const evidence=await ds.getRepository(ScreeningEvidence).save({screening,category:EvidenceCategory.IDENTITY,storageProvider:'s3-compatible',storageKey:'screening/guard/'+guard1.id+'/11111111-1111-4111-8111-111111111111',originalFileName:'identity.pdf',mimeType:'application/pdf',sizeBytes:'100',uploadCompletedAt:new Date(),verificationState:VerificationState.VERIFIED,uploadedByUserId:guard1.user.id,verifiedByUserId:admin.id,verifiedAt:new Date()});
  await ds.getRepository(ScreeningConsent).save({screening,consentVersion:'S4-PILOT-1',candidateUserId:guard1.user.id,acceptedAt:new Date()});
  const jwt=new JwtService({secret:process.env.JWT_SECRET});const token=(u:User)=>jwt.sign({sub:u.id,email:u.email,role:u.role,status:u.status,principalType:'user'});const call=(path:string,u:User,init:RequestInit={})=>fetch(base+path,{...init,headers:{authorization:`Bearer ${token(u)}`,'content-type':'application/json',...(init.headers||{})}});
  const company=await ds.getRepository(Company).findOneByOrFail({user:{id:companyUser.id}});guard2.siaExpiryDate='2030-01-01';guard2.rightToWorkStatus='verified';guard2.rightToWorkExpiryDate='2030-01-01';await guards.save(guard2);await ds.getRepository(GuardDocument).delete({guard:{id:guard2.id}});for(const type of [GuardDocumentType.SIA_LICENCE,GuardDocumentType.RIGHT_TO_WORK])await ds.getRepository(GuardDocument).save({guard:guard2,company,type,storageProvider:'s3-compatible',storageKey:`compliance/company/${company.id}/${guard2.id}/${type===GuardDocumentType.SIA_LICENCE?'22222222-2222-4222-8222-222222222222':'33333333-3333-4333-8333-333333333333'}`,originalFileName:`${type}.pdf`,mimeType:'application/pdf',sizeBytes:'100',uploadCompletedAt:new Date(),expiryDate:'2030-01-01',verified:true,uploadedByUserId:companyUser.id,verifiedByUserId:companyUser.id,verifiedAt:new Date()});
  await ds.getRepository(Job).update({title:'Fixture Job'},{guardsRequired:2,status:'open'});
  await ds.getRepository(CompanyGuard).delete({guard:{id:guard2.id}});let response=await call('/company-guards',admin,{method:'POST',body:JSON.stringify({companyId:company.id,guardId:guard2.id,relationshipType:'approved_contractor',status:'ACTIVE'})});assert.equal(response.status,403);assert.equal(await ds.getRepository(CompanyGuard).count({where:{guard:{id:guard2.id}}}),0);pass('ACTIVE CompanyGuard cannot be created for an unvetted Guard');
  const job=await ds.getRepository(Job).findOneOrFail({where:{title:'Fixture Job'}});await ds.getRepository(JobApplication).delete({guard:{id:guard2.id}});response=await call('/jobs',guard2.user);assert.equal(response.status,200);assert.ok((await response.json() as any[]).some(x=>x.id===job.id));pass('Unvetted ACTIVE Guard browses advertised jobs');response=await call(`/jobs/${job.id}`,guard2.user);assert.equal(response.status,200);pass('Unvetted ACTIVE Guard opens job details');response=await call('/job-applications/self',guard2.user,{method:'POST',body:JSON.stringify({jobId:job.id})});assert.ok(response.status===200||response.status===201);const application=await response.json() as any;pass('Unvetted ACTIVE Guard submits application');response=await call('/job-applications/self',guard2.user);assert.equal(response.status,200);assert.ok((await response.json() as any[]).some(x=>x.id===application.id));pass('Unvetted Guard views application status');
  const linksBefore=await ds.getRepository(CompanyGuard).count({where:{guard:{id:guard2.id}}});const assignmentsBefore=await ds.getRepository(Assignment).count({where:{guard:{id:guard2.id}}});response=await call(`/job-applications/${application.id}/hire`,companyUser,{method:'POST',body:JSON.stringify({createShift:false})});assert.equal(response.status,403);assert.match(await response.text(),/Guard screening is not complete/);assert.equal(await ds.getRepository(CompanyGuard).count({where:{guard:{id:guard2.id}}}),linksBefore);assert.equal(await ds.getRepository(Assignment).count({where:{guard:{id:guard2.id}}}),assignmentsBefore);pass('Hire gate rejects unvetted Guard without partial engagement');
  response=await call('/screening/mine',guard1.user);assert.equal(response.status,200);const mineText=await response.text();JSON.parse(mineText);assert.ok(!mineText.includes('storageKey')&&!mineText.includes('11111111-1111'));pass('Guard accesses own screening with finite safe serialization');
  response=await call(`/screening/${screening.id}`,guard2.user);assert.equal(response.status,403);pass('Guard cannot access another Guard aggregate');
  response=await call(`/screening/${screening.id}/checks/identity`,guard1.user,{method:'PATCH',body:JSON.stringify({state:'VERIFIED',method:'forged'})});assert.equal(response.status,403);pass('Guard cannot verify own checks');
  response=await call(`/screening/${screening.id}/complete`,guard1.user,{method:'POST',body:JSON.stringify({reason:'forged'})});assert.equal(response.status,403);pass('Guard cannot set VETTED');
  response=await call(`/screening/${screening.id}`,companyUser);assert.equal(response.status,403);pass('Company cannot access screening aggregate');
  response=await call(`/screening/evidence/${evidence.id}/access`,companyUser);assert.equal(response.status,403);pass('Company cannot access screening evidence');
  response=await call('/screening',client);assert.equal(response.status,403);pass('Client role cannot access screening');
  response=await call(`/screening/${screening.id}`,admin);assert.equal(response.status,200);const adminText=await response.text();JSON.parse(adminText);assert.ok(!adminText.includes('storageKey'));pass('Platform Admin can access reviewer aggregate without storage key');
  response=await call(`/screening/evidence/${evidence.id}/access`,guard2.user);assert.equal(response.status,403);pass('Private evidence ownership is enforced cross-guard');
  response=await call(`/screening/evidence/${evidence.id}/access`,admin);assert.equal(response.status,200);const accessText=await response.text();assert.ok(!accessText.includes('storageKey'));pass('Authorised evidence access is finite and excludes storage key');
  response=await call(`/screening/company/guards/${guard1.id}/outcome`,companyUser);assert.equal(response.status,200);const outcome=await response.json() as Record<string,unknown>;assert.deepEqual(Object.keys(outcome).sort(),['guardId','status','vetted']);pass('Company outcome excludes private screening data');
  response=await call(`/screening/${screening.id}/checks/identity`,admin,{method:'PATCH',body:JSON.stringify({state:'VERIFIED',method:'Independent test verification'})});assert.equal(response.status,200);pass('Platform Admin verification route succeeds');
  response=await call(`/screening/${screening.id}/complete`,admin,{method:'POST',body:JSON.stringify({reason:'All configured pilot controls verified.'})});assert.ok(response.status===200||response.status===201);const completed=await response.json() as any;assert.equal(completed.status,ScreeningStatus.VETTED);pass('Platform Admin completes valid screening');
  response=await call('/screening/mine/consent/withdraw',guard1.user,{method:'POST'});assert.ok(response.status===200||response.status===201);response=await call('/screening/mine',guard1.user);assert.equal((await response.json() as any).status,ScreeningStatus.REQUIRES_ATTENTION);pass('Consent withdrawal invalidates VETTED status');
  response=await call('/screening/mine/consent',guard1.user,{method:'POST',body:JSON.stringify({consentVersion:'S4-PILOT-2'})});assert.ok(response.status===200||response.status===201);pass('New explicit consent can be accepted after withdrawal');
  const actions=(await ds.getRepository(AuditLog).find({where:{entityType:'GuardScreening',entityId:screening.id}})).map(x=>x.action);for(const action of ['screening.check_verified','screening.consent_accepted','screening.consent_withdrawn','screening.evidence_accessed'])assert.ok(actions.includes(action),`Missing ${action}`);pass('Required remediation audit actions are persisted');
  console.log(JSON.stringify({event:'screening_api_postgres_tests_passed',tests:passed}));
 }finally{await app.close();}
}
main().catch(e=>{console.error(e);process.exit(1);});
