# S4 pilot Android release build — produces the release-signed pilot APK.
#
# Signing secrets NEVER appear in this file, in any Gradle file, in Git, or in build logs:
#   - the keystore and its password live in one ACL-protected file outside the repository, held by the release
#     owner (default: %USERPROFILE%\.s4-pilot-secrets\android-signing.properties)
#   - this script loads them into ORG_GRADLE_PROJECT_* environment variables for the build process only
#   - the injected Gradle signingConfig references those properties BY NAME, never by value
#   - android/ is generated by `expo prebuild` and is gitignored, so the injected config never enters Git
#
# See docs/runbooks/DEPLOYMENT.md - "Android release signing key" for the key, its backup rules and the
# expected certificate fingerprint.
#
# Usage, from security-mobile-app\scripts:
#   .\build-pilot-apk.ps1 -ApiUrl https://<pilot-api-host>
#   .\build-pilot-apk.ps1 -ApiUrl https://<pilot-api-host> -SecretsFile <path to the signing properties file>
#
# Build the pilot APK only AFTER the pilot backend is deployed, so the final HTTPS API URL is embedded.
param(
  [Parameter(Mandatory = $true)][string]$ApiUrl,
  [string]$SecretsFile = "$env:USERPROFILE\.s4-pilot-secrets\android-signing.properties",
  [string]$WorkRoot = 'C:\s4-pilot-build',
  [string]$OutDir = "$env:USERPROFILE\.s4-pilot-secrets\artifacts"
)
$ErrorActionPreference = 'Continue'
function Write-NoBom($path, $text) { [IO.File]::WriteAllText($path, $text, (New-Object Text.UTF8Encoding $false)) }

if ($ApiUrl -notmatch '^https://') { throw "ApiUrl must be HTTPS for a pilot build (got '$ApiUrl')." }
if (-not (Test-Path $SecretsFile)) { throw "Signing secrets file not found: $SecretsFile" }

# ── Load signing secrets into the build process environment only ─────────────────────────────────
$secrets = @{}
foreach ($line in Get-Content $SecretsFile) {
  if ($line -match '^\s*#' -or $line -notmatch '=') { continue }
  $i = $line.IndexOf('='); $secrets[$line.Substring(0, $i).Trim()] = $line.Substring($i + 1).Trim()
}
foreach ($k in 'S4_RELEASE_STORE_FILE', 'S4_RELEASE_KEY_ALIAS', 'S4_RELEASE_STORE_PASSWORD', 'S4_RELEASE_KEY_PASSWORD') {
  if (-not $secrets[$k]) { throw "$k missing from $SecretsFile" }
  Set-Item -Path "env:ORG_GRADLE_PROJECT_$k" -Value $secrets[$k]   # Gradle reads this as project property $k
}
if (-not (Test-Path $secrets['S4_RELEASE_STORE_FILE'])) { throw "Keystore not found: $($secrets['S4_RELEASE_STORE_FILE'])" }

$repo = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)   # …/security-mobile-app/scripts → repo root
if (-not (Test-Path "$repo\.git")) { throw "Run this script from security-mobile-app\scripts inside the repository (resolved '$repo')." }
$app = "$WorkRoot\security-mobile-app"
$env:JAVA_HOME = 'C:\Program Files\Android\Android Studio\jbr'
$env:ANDROID_HOME = "$env:LOCALAPPDATA\Android\Sdk"
$env:ANDROID_SDK_ROOT = $env:ANDROID_HOME
$env:PATH = "$env:JAVA_HOME\bin;$env:ANDROID_HOME\platform-tools;$env:PATH"
$env:EXPO_PUBLIC_API_URL = $ApiUrl          # inlined into the JS bundle by Metro
$env:CI = '1'; $env:EXPO_NO_TELEMETRY = '1'

# ── Clean tree from the committed release SHA only (never the working copy: no untracked src/dev) ──
if (Test-Path $WorkRoot) { cmd /c rmdir /s /q $WorkRoot }
New-Item -ItemType Directory $WorkRoot | Out-Null
$sha = (git -C $repo rev-parse HEAD).Trim()
# Write the archive to a file: piping it through PowerShell corrupts the binary stream ("Unrecognized archive format").
$tar = "$env:TEMP\s4-pilot-src.tar"
git -C $repo archive --format=tar -o $tar HEAD security-mobile-app
tar -xf $tar -C $WorkRoot
Remove-Item $tar -Force
# Copy node_modules rather than junctioning it: with a junction Metro resolves App.tsx through the real repo path
# and the release bundle fails ("Unable to resolve module ../../App").
robocopy "$repo\security-mobile-app\node_modules" "$app\node_modules" /MIR /MT:32 /NFL /NDL /NJH /NJS /NP | Out-Null
Set-Location $app
npx expo prebuild --platform android --no-install

# ── Inject the signing config: property NAMES only, no values ────────────────────────────────────
$gradlePath = "$app\android\app\build.gradle"
$gradle = Get-Content $gradlePath -Raw
$signing = @'
    signingConfigs {
        release {
            // Values come from ORG_GRADLE_PROJECT_* environment variables supplied by build-pilot-apk.ps1.
            // Never hard-code them here: this file is generated into a gitignored android/ directory.
            storeFile file(project.findProperty('S4_RELEASE_STORE_FILE') ?: { throw new GradleException('S4_RELEASE_STORE_FILE not set') }())
            storePassword project.findProperty('S4_RELEASE_STORE_PASSWORD') ?: { throw new GradleException('S4_RELEASE_STORE_PASSWORD not set') }()
            keyAlias project.findProperty('S4_RELEASE_KEY_ALIAS') ?: { throw new GradleException('S4_RELEASE_KEY_ALIAS not set') }()
            keyPassword project.findProperty('S4_RELEASE_KEY_PASSWORD') ?: { throw new GradleException('S4_RELEASE_KEY_PASSWORD not set') }()
            enableV2Signing true
            enableV3Signing true   // v3 carries a rotation proof, so the key can be rotated on Android 9+ later
        }

'@
$gradle = $gradle -replace '    signingConfigs \{\r?\n', $signing
$gradle = [regex]::Replace($gradle, '(buildTypes \{[\s\S]*?release \{[\s\S]*?)signingConfig signingConfigs\.debug', '$1signingConfig signingConfigs.release')
Write-NoBom $gradlePath $gradle                                    # Set-Content -Encoding utf8 writes a BOM Gradle rejects

# Devices (arm64) + emulator (x86_64). No cleartext permission: the pilot app talks HTTPS only.
(Get-Content "$app\android\gradle.properties") -replace 'reactNativeArchitectures=.*', 'reactNativeArchitectures=arm64-v8a,x86_64' |
  Out-String | ForEach-Object { Write-NoBom "$app\android\gradle.properties" $_ }

Remove-Item -Recurse -Force "$env:TEMP\metro-cache" -ErrorAction SilentlyContinue   # else the previous API URL is reused
Set-Location "$app\android"
.\gradlew.bat assembleRelease --no-daemon --console=plain

# ── Collect + verify ─────────────────────────────────────────────────────────────────────────────
$apk = Get-ChildItem "$app\android\app\build\outputs\apk\release" -Filter *.apk -ErrorAction SilentlyContinue | Select-Object -First 1
if (-not $apk) { throw 'Build failed: no APK produced.' }
if (-not (Test-Path $OutDir)) { New-Item -ItemType Directory $OutDir | Out-Null }
$out = "$OutDir\s4-pilot-$($sha.Substring(0,7)).apk"
Copy-Item $apk.FullName $out -Force
& "$env:ANDROID_HOME\build-tools\36.0.0\apksigner.bat" verify --verbose --print-certs $out
Write-Host "APK: $out (commit $sha, API $ApiUrl)"
