const assert=require('assert'),fs=require('fs'),path=require('path');let passed=0;
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8');
const panel=read('src/components/guard/GuardScreeningPanel.tsx'),guard=read('src/screens/GuardDashboardScreen.tsx'),jobs=read('src/screens/JobsScreen.tsx'),admin=read('src/screens/AdminDashboardScreen.tsx'),company=read('src/components/company/CompanyComplianceWorkspace.tsx'),api=read('src/services/api.ts'),models=read('src/types/models.ts'),service=read('../security-backend-nest/src/screening/screening.service.ts'),controller=read('../security-backend-nest/src/screening/screening.controller.ts'),eligibility=read('../security-backend-nest/src/compliance/compliance.service.ts');
function test(name,fn){fn();passed++;console.log(`PASS ${name}`)}
test('ACTIVE unvetted Guard sees screening progress',()=>assert.match(panel,/Marketplace access: Available[\s\S]*Work eligibility:/));
test('ACTIVE unvetted Guard still sees Jobs',()=>assert.match(guard,/\['jobs', 'Jobs'\]/));
test('ACTIVE unvetted Guard can still apply',()=>{assert.doesNotMatch(jobs,/VETTED|screening/i);assert.match(jobs,/appl/i)});
test('dedicated screening navigation works',()=>{assert.match(guard,/activeTab === 'screening'/);assert.match(panel,/STEPS\.map/)});
test('progress reflects backend response',()=>assert.match(panel,/data\.progress/));
test('personal details can be saved',()=>assert.match(panel,/updateMyScreeningProfile\(profile\)/));
test('address history can be maintained',()=>assert.match(panel,/addMyScreeningAddress/));
test('activity chronology can be maintained',()=>assert.match(panel,/addMyScreeningHistory/));
test('backend-detected gap is displayed',()=>assert.match(panel,/requirements\?\.chronology\.gaps/));
test('backend-detected overlap is displayed',()=>assert.match(panel,/requirements\?\.chronology\.overlaps/));
test('references can be maintained',()=>assert.match(panel,/addMyScreeningReference/));
test('evidence workflow uses signed private upload',()=>{assert.match(panel,/created\.upload\.url/);assert.match(panel,/completeMyScreeningEvidence/);assert.match(service,/createSignedUploadUrl/)});
test('Guard cannot self-verify evidence',()=>assert.doesNotMatch(panel,/verifyScreeningCheck|verificationState\s*:/));
test('Guard cannot self-mark VETTED',()=>assert.doesNotMatch(panel,/status\s*:\s*['"]VETTED/));
test('consent acceptance works',()=>assert.match(panel,/acceptMyScreeningConsent/));
test('consent withdrawal works',()=>assert.match(panel,/withdrawMyScreeningConsent/));
test('submission displays missing requirements',()=>assert.match(panel,/requirements\?\.missing\.map/));
for(const status of ['READY_FOR_REVIEW','UNDER_REVIEW','VETTED','REQUIRES_ATTENTION','REJECTED','EXPIRED'])test(`${status} has a human-readable presentation`,()=>assert.match(panel,new RegExp(`${status}:'[^']+'`)));
test('company cannot access private screening information',()=>{assert.doesNotMatch(company,/screening\/evidence|dateOfBirth|reviewNotes|storageKey|signedUrl/);assert.match(service,/companyOutcome/)});
test('company-safe outcome remains minimal',()=>assert.match(service,/return \{guardId,status:s\?\.status\?\?ScreeningStatus\.NOT_STARTED,vetted:/));
test('reviewer authorization remains ADMIN-only',()=>assert.match(controller,/@Roles\(UserRole\.ADMIN\)[\s\S]*start-review/));
test('Admin reviewer sees chronology and gaps',()=>{assert.match(admin,/Activity chronology/);assert.match(admin,/Unexplained period/)});
test('Admin reviewer does not render private storage values',()=>assert.doesNotMatch(admin,/storageKey|signedUrl|upload\.url/));
test('suspended and inactive account eligibility remains fail-closed',()=>assert.match(eligibility,/UserStatus\.ACTIVE/));
test('unvetted hiring remains server-blocked',()=>assert.match(eligibility,/isGuardVetted|screening/i));
test('vetted compliant ACTIVE eligibility path remains server-derived',()=>{assert.match(eligibility,/UserStatus\.ACTIVE/);assert.match(eligibility,/compliance/i);assert.match(eligibility,/screening|VETTED/i)});
test('profile contains compact summary, not workflow form',()=>{assert.match(panel,/YOUR VETTING & SCREENING/);assert.match(guard,/GuardScreeningPanel onContinue/)});
test('SIA and Right to Work are distinct checks',()=>{assert.match(panel,/SIA register verification/);assert.match(panel,/Right to Work verification/)});
test('verification language separates upload and review',()=>assert.match(panel,/Upload does not prove reviewer verification/));
test('explicit labels and controlled feedback are present',()=>{assert.match(panel,/accessibilityLabel=\{label\}/);assert.match(panel,/Personal details saved/);assert.match(panel,/accessibilityRole="alert"/)});
test('responsive step navigation avoids a desktop-only form',()=>assert.match(panel,/ScrollView horizontal/));
test('API exposes no client VETTED mutation',()=>assert.doesNotMatch(api,/status\s*:\s*['"]VETTED|setVetted/));
test('model includes server consent and verification state',()=>{assert.match(models,/consents\?/);assert.match(models,/identityVerification\?/)});
console.log(JSON.stringify({event:'screening_ux_tests_passed',tests:passed}));
