import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { randomUUID } from 'crypto';
import { IsNull, Repository } from 'typeorm';
import { AuditLogService } from '../audit-log/audit-log.service';
import { CompanyGuard, CompanyGuardStatus } from '../company-guard/entities/company-guard.entity';
import { CompanyService } from '../company/company.service';
import { EvidenceStorageService } from '../compliance/evidence-storage.service';
import { GuardProfileService } from '../guard-profile/guard-profile.service';
import { JwtPayload } from '../auth/types/jwt-payload.type';
import { isSiaUniqueViolation } from '../auth/auth.service';
import { UserRole } from '../user/entities/user.entity';
import { AddAddressDto, AddHistoryDto, AddReferenceDto, ConsentDto, CreateEvidenceDto, ReviewActionDto, ReviewReferenceDto, StartScreeningDto, UpdateCandidateComplianceDto, UpdateScreeningProfileDto, VerifyCheckDto } from './dto/screening.dto';
import { GuardScreening, ReferenceStatus, ScreeningAddress, ScreeningConsent, ScreeningEvidence, ScreeningException, ScreeningHistory, ScreeningReference, ScreeningStatus, VerificationState } from './entities/screening.entities';

type Interval = { startDate: string; endDate?: string | null; isCurrent: boolean };
const UK_POSTCODE = /^(GIR 0AA|[A-Z]{1,2}\d[A-Z\d]? \d[A-Z]{2})$/;
export function normalizeUkPostcode(value:string){const compact=value.trim().toUpperCase().replace(/\s+/g,'');if(compact==='GIR0AA')return 'GIR 0AA';if(compact.length<5||compact.length>7)throw new BadRequestException('Enter a valid UK postcode.');const normalized=`${compact.slice(0,-3)} ${compact.slice(-3)}`;if(!UK_POSTCODE.test(normalized))throw new BadRequestException('Enter a valid UK postcode.');return normalized;}
export function assessContinuousHistory(entries: Interval[], years: number, now = new Date()) {
  const end = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));
  const start = new Date(end); start.setUTCFullYear(start.getUTCFullYear() - years);
  const clipped = entries.map((entry) => {
    const from = new Date(`${entry.startDate}T00:00:00Z`);
    const to = entry.isCurrent ? end : new Date(`${entry.endDate}T00:00:00Z`);
    if (Number.isNaN(from.getTime()) || Number.isNaN(to.getTime()) || to < from) throw new BadRequestException('History dates are invalid.');
    return { from: from < start ? start : from, to: to > end ? end : to };
  }).filter((x) => x.to >= start && x.from <= end).sort((a, b) => a.from.getTime() - b.from.getTime());
  const gaps: { from: string; to: string }[] = []; const overlaps: { from: string; to: string }[] = [];
  let cursor = start;
  for (const item of clipped) {
    if (item.from > cursor) gaps.push({ from: cursor.toISOString().slice(0,10), to: new Date(item.from.getTime()-86400000).toISOString().slice(0,10) });
    if (item.from < cursor) { const overlapEnd = new Date(Math.min(item.to.getTime(), cursor.getTime()-86400000)); if (overlapEnd >= item.from) overlaps.push({ from: item.from.toISOString().slice(0,10), to: overlapEnd.toISOString().slice(0,10) }); }
    if (item.to >= cursor) cursor = new Date(item.to.getTime()+86400000);
  }
  if (cursor <= end) gaps.push({ from: cursor.toISOString().slice(0,10), to: end.toISOString().slice(0,10) });
  return { continuous: gaps.length === 0, gaps, overlaps, periodStart: start.toISOString().slice(0,10), periodEnd: end.toISOString().slice(0,10) };
}

@Injectable()
export class ScreeningService {
  constructor(
    @InjectRepository(GuardScreening) private readonly screenings: Repository<GuardScreening>,
    @InjectRepository(ScreeningHistory) private readonly history: Repository<ScreeningHistory>,
    @InjectRepository(ScreeningAddress) private readonly addresses: Repository<ScreeningAddress>,
    @InjectRepository(ScreeningReference) private readonly references: Repository<ScreeningReference>,
    @InjectRepository(ScreeningEvidence) private readonly evidence: Repository<ScreeningEvidence>,
    @InjectRepository(ScreeningConsent) private readonly consents: Repository<ScreeningConsent>,
    @InjectRepository(ScreeningException) private readonly exceptions: Repository<ScreeningException>,
    @InjectRepository(CompanyGuard) private readonly companyGuards: Repository<CompanyGuard>,
    private readonly guards: GuardProfileService, private readonly companies: CompanyService,
    private readonly audit: AuditLogService, private readonly storage: EvidenceStorageService,
  ) {}

  private async byGuardUser(userId: number) { const guard = await this.guards.findByUserId(userId); if (!guard) throw new NotFoundException('Guard profile not found.'); return { guard, screening: await this.screenings.findOne({ where: { guard: { id: guard.id } }, relations: ['history','addresses','references','evidence','consents','exceptions'] }) }; }
  private async full(id: number) { const value = await this.screenings.findOne({ where: { id }, relations: ['history','addresses','references','evidence','consents','exceptions'] }); if (!value) throw new NotFoundException('Screening file not found.'); return value; }
  private editable(s: GuardScreening) { if (![ScreeningStatus.NOT_STARTED, ScreeningStatus.IN_PROGRESS, ScreeningStatus.REQUIRES_ATTENTION].includes(s.status)) throw new BadRequestException('Screening file is not editable in its current state.'); }
  private editableRecordCorrection(s:GuardScreening){if(![ScreeningStatus.NOT_STARTED,ScreeningStatus.IN_PROGRESS,ScreeningStatus.READY_FOR_REVIEW,ScreeningStatus.REQUIRES_ATTENTION].includes(s.status))throw new BadRequestException('Screening records are not editable in the current state.');}
  private async event(actor: number, action: string, s: GuardScreening, before?: Record<string,unknown>, after?: Record<string,unknown>) { await this.audit.log({ user:{id:actor}, action, entityType:'GuardScreening', entityId:s.id, beforeData:before, afterData:after }); }
  private async reopenAfterCandidateCorrection(actor:number,s:GuardScreening){if(s.status!==ScreeningStatus.READY_FOR_REVIEW)return;const submittedAt=s.submittedAt;s.status=ScreeningStatus.IN_PROGRESS;s.submittedAt=null;await this.screenings.save(s);await this.event(actor,'screening.candidate_correction_reopened',s,{status:ScreeningStatus.READY_FOR_REVIEW,submittedAt:submittedAt?.toISOString()},{status:s.status,submittedAt:null});}
  async start(userId:number,dto:StartScreeningDto) { const {guard,screening}=await this.byGuardUser(userId); if(screening) return this.view(screening); const saved=await this.screenings.save(this.screenings.create({guard,status:ScreeningStatus.IN_PROGRESS,screeningPeriodYears:dto.screeningPeriodYears??5})); await this.event(userId,'screening.started',saved,undefined,{status:saved.status,screeningPeriodYears:saved.screeningPeriodYears}); return this.view(await this.full(saved.id)); }
  async mine(userId:number) { const {screening}=await this.byGuardUser(userId); return screening ? this.view(screening) : {status:ScreeningStatus.NOT_STARTED,progress:0,missing:['Screening file has not been started.']}; }
  async updateProfile(userId:number,dto:UpdateScreeningProfileDto){const {screening}=await this.byGuardUser(userId);if(!screening)throw new BadRequestException('Start screening first.');this.editable(screening);const updates={...dto,previousNames:dto.previousNames?.trim()||null,siaLicenceType:dto.siaLicenceType?.trim()||null,status:ScreeningStatus.IN_PROGRESS};if(dto.currentAddress===undefined)delete updates.currentAddress;Object.assign(screening,updates);await this.screenings.save(screening);return this.view(await this.full(screening.id));}
  async updateCandidateCompliance(userId:number,dto:UpdateCandidateComplianceDto){const {guard,screening}=await this.byGuardUser(userId);if(!screening)throw new BadRequestException('Start screening first.');const before={siaLicenseNumber:guard.siaLicenseNumber,siaExpiryDate:guard.siaExpiryDate,rightToWorkStatus:guard.rightToWorkStatus,rightToWorkExpiryDate:guard.rightToWorkExpiryDate};const siaRequested=(dto.siaLicenseNumber!==undefined&&dto.siaLicenseNumber!==before.siaLicenseNumber)||(dto.siaExpiryDate!==undefined&&dto.siaExpiryDate!==before.siaExpiryDate);const rtwRequested=(dto.rightToWorkStatus!==undefined&&dto.rightToWorkStatus!==before.rightToWorkStatus)||(dto.rightToWorkExpiryDate!==undefined&&dto.rightToWorkExpiryDate!==before.rightToWorkExpiryDate);if(screening.status===ScreeningStatus.READY_FOR_REVIEW){const actions=this.requirements(screening).remediation.filter(x=>x.status==='ACTION_REQUIRED').map(x=>x.key);if(siaRequested&&!actions.some(x=>x==='sia_expiry'||x==='sia_check'))throw new BadRequestException('SIA correction is not currently required.');if(rtwRequested&&!actions.some(x=>x==='rtw_status'||x==='rtw_check'))throw new BadRequestException('Right-to-Work correction is not currently required.');if(!siaRequested&&!rtwRequested)throw new BadRequestException('No candidate compliance correction was supplied.');}else this.editable(screening);let saved;try{saved=await this.guards.updateByUserId(userId,dto);}catch(error){if(isSiaUniqueViolation(error))throw new ConflictException('SIA licence number is already registered.');throw error;}const siaChanged=before.siaLicenseNumber!==saved.siaLicenseNumber||before.siaExpiryDate!==saved.siaExpiryDate;const rtwChanged=before.rightToWorkStatus!==saved.rightToWorkStatus||before.rightToWorkExpiryDate!==saved.rightToWorkExpiryDate;if(siaChanged)Object.assign(screening,{siaRegisterVerification:VerificationState.UNVERIFIED,siaVerifiedByUserId:null,siaVerifiedAt:null});if(rtwChanged)Object.assign(screening,{rightToWorkVerification:VerificationState.UNVERIFIED,rightToWorkCheckMethod:null,rightToWorkCheckDate:null,rightToWorkVerifiedByUserId:null,rightToWorkVerifiedAt:null});if(siaChanged||rtwChanged)await this.screenings.save(screening);await this.reopenAfterCandidateCorrection(userId,screening);await this.event(userId,'screening.candidate_compliance_updated',screening,undefined,{siaChanged,rtwChanged});return this.view(await this.full(screening.id));}
  async addHistory(userId:number,dto:AddHistoryDto){const {screening}=await this.byGuardUser(userId);if(!screening)throw new BadRequestException('Start screening first.');this.editableRecordCorrection(screening);if(dto.isCurrent&&dto.endDate)throw new BadRequestException('A current period cannot have an end date.');if(!dto.isCurrent&&!dto.endDate)throw new BadRequestException('An end date is required.');const saved=await this.history.save(this.history.create({...dto,endDate:dto.isCurrent?null:dto.endDate,screening}));await this.reopenAfterCandidateCorrection(userId,screening);await this.event(userId,'screening.history_added',screening,undefined,{historyId:saved.id,type:saved.type,startDate:saved.startDate,endDate:saved.endDate});return {id:saved.id,type:saved.type,startDate:saved.startDate,endDate:saved.endDate,isCurrent:saved.isCurrent,organisation:saved.organisation,description:saved.description,verificationState:saved.verificationState};}
  async updateHistory(userId:number,id:number,dto:AddHistoryDto){const {screening}=await this.byGuardUser(userId);if(!screening)throw new BadRequestException('Start screening first.');this.editableRecordCorrection(screening);const record=await this.history.findOne({where:{id},relations:['screening']});if(!record||record.screening.id!==screening.id)throw new ForbiddenException('History entry is not part of this screening file.');if(dto.isCurrent&&dto.endDate)throw new BadRequestException('A current period cannot have an end date.');if(!dto.isCurrent&&!dto.endDate)throw new BadRequestException('An end date is required.');const before={type:record.type,startDate:record.startDate,endDate:record.endDate,isCurrent:record.isCurrent};Object.assign(record,{...dto,endDate:dto.isCurrent?null:dto.endDate,verificationState:VerificationState.UNVERIFIED});const saved=await this.history.save(record);await this.reopenAfterCandidateCorrection(userId,screening);await this.event(userId,'screening.history_updated',screening,before,{historyId:saved.id,type:saved.type,startDate:saved.startDate,endDate:saved.endDate,isCurrent:saved.isCurrent});return this.view(await this.full(screening.id));}
  async deleteHistory(userId:number,id:number){const {screening}=await this.byGuardUser(userId);if(!screening)throw new BadRequestException('Start screening first.');this.editableRecordCorrection(screening);const record=await this.history.findOne({where:{id},relations:['screening']});if(!record||record.screening.id!==screening.id)throw new ForbiddenException('History entry is not part of this screening file.');const before={historyId:record.id,type:record.type,startDate:record.startDate,endDate:record.endDate};await this.history.remove(record);await this.reopenAfterCandidateCorrection(userId,screening);await this.event(userId,'screening.history_deleted',screening,before,undefined);return this.view(await this.full(screening.id));}
  async addAddress(userId:number,dto:AddAddressDto){const {screening}=await this.byGuardUser(userId);if(!screening)throw new BadRequestException('Start screening first.');this.editableRecordCorrection(screening);const saved=await this.addresses.save(this.addresses.create({...this.addressValues(dto),screening}));await this.reopenAfterCandidateCorrection(userId,screening);return {id:saved.id,address:saved.address,addressLine1:saved.addressLine1,addressLine2:saved.addressLine2,townCity:saved.townCity,postcode:saved.postcode,startDate:saved.startDate,endDate:saved.endDate,isCurrent:saved.isCurrent,verificationState:saved.verificationState};}
  private addressValues(dto:AddAddressDto){if(dto.isCurrent&&dto.endDate)throw new BadRequestException('A current address cannot have an end date.');if(!dto.isCurrent&&!dto.endDate)throw new BadRequestException('An end date is required.');const structured=[dto.addressLine1,dto.addressLine2,dto.townCity,dto.postcode].some(v=>v!==undefined);if(structured){const addressLine1=dto.addressLine1?.trim(),townCity=dto.townCity?.trim(),postcode=dto.postcode?normalizeUkPostcode(dto.postcode):'';if(!addressLine1||!townCity||!postcode)throw new BadRequestException('Address line 1, town or city, and postcode are required.');const addressLine2=dto.addressLine2?.trim()||null;return {address:[addressLine1,addressLine2,townCity,postcode].filter(Boolean).join('\n'),addressLine1,addressLine2,townCity,postcode,startDate:dto.startDate,endDate:dto.isCurrent?null:dto.endDate,isCurrent:dto.isCurrent};}const address=dto.address?.trim();if(!address)throw new BadRequestException('Address is required.');return {address,addressLine1:null,addressLine2:null,townCity:null,postcode:null,startDate:dto.startDate,endDate:dto.isCurrent?null:dto.endDate,isCurrent:dto.isCurrent};}
  async updateAddress(userId:number,id:number,dto:AddAddressDto){const {screening}=await this.byGuardUser(userId);if(!screening)throw new BadRequestException('Start screening first.');this.editableRecordCorrection(screening);const record=await this.addresses.findOne({where:{id},relations:['screening']});if(!record||record.screening.id!==screening.id)throw new ForbiddenException('Address entry is not part of this screening file.');const before={addressId:record.id,startDate:record.startDate,endDate:record.endDate,isCurrent:record.isCurrent};Object.assign(record,this.addressValues(dto),{verificationState:VerificationState.UNVERIFIED});const saved=await this.addresses.save(record);await this.reopenAfterCandidateCorrection(userId,screening);await this.event(userId,'screening.address_updated',screening,before,{addressId:saved.id,startDate:saved.startDate,endDate:saved.endDate,isCurrent:saved.isCurrent});return this.view(await this.full(screening.id));}
  async deleteAddress(userId:number,id:number){const {screening}=await this.byGuardUser(userId);if(!screening)throw new BadRequestException('Start screening first.');this.editableRecordCorrection(screening);const record=await this.addresses.findOne({where:{id},relations:['screening']});if(!record||record.screening.id!==screening.id)throw new ForbiddenException('Address entry is not part of this screening file.');const before={addressId:record.id,startDate:record.startDate,endDate:record.endDate,isCurrent:record.isCurrent};await this.addresses.remove(record);await this.reopenAfterCandidateCorrection(userId,screening);await this.event(userId,'screening.address_deleted',screening,before,undefined);return this.view(await this.full(screening.id));}
  async addReference(userId:number,dto:AddReferenceDto){const {screening}=await this.byGuardUser(userId);if(!screening)throw new BadRequestException('Start screening first.');this.editable(screening);const history=await this.history.findOne({where:{id:dto.historyId},relations:['screening']});if(!history||history.screening.id!==screening.id)throw new ForbiddenException('History entry is not part of this screening file.');const saved=await this.references.save(this.references.create({...dto,screening,history}));return this.safeReference(saved);}
  async consent(userId:number,dto:ConsentDto){const {screening}=await this.byGuardUser(userId);if(!screening)throw new BadRequestException('Start screening first.');this.editable(screening);const current=await this.consents.find({where:{screening:{id:screening.id},withdrawnAt:IsNull()}});for(const consent of current){consent.withdrawnAt=new Date();await this.consents.save(consent);await this.event(userId,'screening.consent_withdrawn',screening,undefined,{consentId:consent.id,consentVersion:consent.consentVersion,withdrawnAt:consent.withdrawnAt.toISOString(),superseded:true});}const saved=await this.consents.save(this.consents.create({screening,consentVersion:dto.consentVersion,candidateUserId:userId,acceptedAt:new Date()}));await this.event(userId,'screening.consent_accepted',screening,undefined,{consentId:saved.id,consentVersion:saved.consentVersion,acceptedAt:saved.acceptedAt.toISOString()});return {id:saved.id,consentVersion:saved.consentVersion,acceptedAt:saved.acceptedAt};}
  async withdrawConsent(userId:number){const {screening}=await this.byGuardUser(userId);if(!screening)throw new BadRequestException('Start screening first.');const current=await this.consents.find({where:{screening:{id:screening.id},withdrawnAt:IsNull()}});if(!current.length)throw new BadRequestException('No current screening consent exists.');for(const consent of current){consent.withdrawnAt=new Date();await this.consents.save(consent);await this.event(userId,'screening.consent_withdrawn',screening,undefined,{consentId:consent.id,consentVersion:consent.consentVersion,withdrawnAt:consent.withdrawnAt.toISOString()});}if([ScreeningStatus.READY_FOR_REVIEW,ScreeningStatus.UNDER_REVIEW,ScreeningStatus.VETTED].includes(screening.status)){const before=screening.status;screening.status=ScreeningStatus.REQUIRES_ATTENTION;screening.vettedAt=null;await this.screenings.save(screening);await this.event(userId,'screening.information_requested',screening,{status:before},{status:screening.status,reason:'Candidate withdrew screening consent.'});}return {withdrawn:true,withdrawnAt:current[0].withdrawnAt};}
  async createEvidence(userId:number,dto:CreateEvidenceDto){const {screening}=await this.byGuardUser(userId);if(!screening)throw new BadRequestException('Start screening first.');if(screening.status===ScreeningStatus.READY_FOR_REVIEW){const action=this.requirements(screening).remediation.find(x=>x.key===`${dto.category}_evidence`);if(action?.status!=='ACTION_REQUIRED')throw new BadRequestException('Evidence is already awaiting verification or verified.');}else this.editable(screening);const mime=dto.mimeType.toLowerCase();if(!['application/pdf','image/jpeg','image/png'].includes(mime))throw new BadRequestException('Evidence must be PDF, JPEG or PNG.');const record=await this.evidence.save(this.evidence.create({screening,category:dto.category,storageProvider:this.storage.provider,storageKey:`screening/guard/${screening.guard.id}/${randomUUID()}`,originalFileName:dto.originalFileName.trim(),mimeType:mime,sizeBytes:String(dto.sizeBytes),uploadedByUserId:userId}));const access=await this.storage.createSignedUploadUrl({key:record.storageKey,mimeType:record.mimeType,originalFileName:record.originalFileName});return {id:record.id,upload:access};}
  private async evidenceFor(id:number){const record=await this.evidence.findOne({where:{id},relations:['screening','screening.guard','screening.guard.user']});if(!record)throw new NotFoundException('Screening evidence not found.');return record;}
  async completeEvidence(user:JwtPayload,id:number){const record=await this.evidenceFor(id);if(user.role!==UserRole.ADMIN&&record.screening.guard.user.id!==user.sub)throw new ForbiddenException();await this.storage.verifyUpload({key:record.storageKey,mimeType:record.mimeType,originalFileName:record.originalFileName},Number(record.sizeBytes));record.uploadCompletedAt=new Date();await this.evidence.save(record);if(user.role===UserRole.GUARD)await this.reopenAfterCandidateCorrection(user.sub,record.screening);await this.event(user.sub,'screening.evidence_uploaded',record.screening,undefined,{evidenceId:record.id,category:record.category,mimeType:record.mimeType,sizeBytes:Number(record.sizeBytes)});return {id:record.id,uploadCompleted:true};}
  async accessEvidence(user:JwtPayload,id:number){const record=await this.evidenceFor(id);if(user.role!==UserRole.ADMIN&&record.screening.guard.user.id!==user.sub)throw new ForbiddenException();if(!record.uploadCompletedAt)throw new BadRequestException('Evidence upload is incomplete.');const access=await this.storage.createSignedDownloadUrl({key:record.storageKey,mimeType:record.mimeType,originalFileName:record.originalFileName});await this.event(user.sub,'screening.evidence_accessed',record.screening,undefined,{evidenceId:record.id,category:record.category,expiresAt:access.expiresAt});return access;}
  async submit(userId:number){const {screening}=await this.byGuardUser(userId);if(!screening)throw new BadRequestException('Start screening first.');this.editable(screening);const result=this.requirements(await this.full(screening.id));if(result.missing.length)throw new BadRequestException(`Screening file is incomplete: ${result.missing[0]}`);const before=screening.status;screening.status=ScreeningStatus.READY_FOR_REVIEW;screening.submittedAt=new Date();await this.screenings.save(screening);await this.event(userId,'screening.submitted',screening,{status:before},{status:screening.status});return this.view(await this.full(screening.id));}
  async listAdmin(){const all=await this.screenings.find({order:{updatedAt:'DESC'}});return Promise.all(all.map(async s=>this.view(await this.full(s.id))));}
  adminGet(id:number){return this.full(id).then(s=>this.view(s,true));}
  async startReview(actor:number,id:number){const s=await this.full(id);if(s.status!==ScreeningStatus.READY_FOR_REVIEW)throw new BadRequestException('Screening file is not ready for review.');s.status=ScreeningStatus.UNDER_REVIEW;s.reviewedByUserId=actor;s.reviewedAt=new Date();await this.screenings.save(s);await this.event(actor,'screening.review_started',s,{status:ScreeningStatus.READY_FOR_REVIEW},{status:s.status});return this.view(await this.full(id),true);}
  async verifyCheck(actor:number,id:number,check:'identity'|'address'|'sia'|'rtw',dto:VerifyCheckDto){const s=await this.full(id);if(s.status!==ScreeningStatus.UNDER_REVIEW)throw new BadRequestException('Screening file is not under review.');const now=new Date();if(check==='identity')Object.assign(s,{identityVerification:dto.state,identityVerificationMethod:dto.method,identityVerifiedByUserId:actor,identityVerifiedAt:now});if(check==='address'){const current=(s.addresses||[]).find(a=>a.isCurrent);if(!current)throw new BadRequestException('Current address is missing.');current.verificationState=dto.state;await this.addresses.save(current);}if(check==='sia')Object.assign(s,{siaRegisterVerification:dto.state,siaVerifiedByUserId:actor,siaVerifiedAt:now});if(check==='rtw')Object.assign(s,{rightToWorkVerification:dto.state,rightToWorkCheckMethod:dto.method,rightToWorkCheckDate:now.toISOString().slice(0,10),rightToWorkVerifiedByUserId:actor,rightToWorkVerifiedAt:now});await this.screenings.save(s);await this.event(actor,'screening.check_verified',s,undefined,{check,state:dto.state,method:dto.method,verifiedAt:now.toISOString()});return this.view(await this.full(id),true);}
  async requestReference(actor:number,id:number){const ref=await this.references.findOne({where:{id},relations:['screening','history']});if(!ref)throw new NotFoundException('Reference not found.');if(ref.screening.status!==ScreeningStatus.UNDER_REVIEW)throw new BadRequestException('Screening file is not under review.');ref.status=ReferenceStatus.REQUESTED;ref.requestedAt=new Date();await this.references.save(ref);await this.event(actor,'screening.reference_requested',ref.screening,undefined,{referenceId:ref.id,status:ref.status});return this.safeReference(ref);}
  async reviewReference(actor:number,id:number,dto:ReviewReferenceDto){const ref=await this.references.findOne({where:{id},relations:['screening','history']});if(!ref)throw new NotFoundException('Reference not found.');if(ref.screening.status!==ScreeningStatus.UNDER_REVIEW)throw new BadRequestException('Screening file is not under review.');if(dto.status===ReferenceStatus.VERIFIED&&!dto.sourceVerified)throw new BadRequestException('Reference source must be verified.');Object.assign(ref,{status:dto.status,sourceVerified:dto.sourceVerified,verificationMethod:dto.verificationMethod,verifiedByUserId:actor,verifiedAt:new Date(),outcomeNotes:dto.notes||null});await this.references.save(ref);await this.event(actor,dto.status===ReferenceStatus.VERIFIED?'screening.reference_verified':'screening.reference_received',ref.screening,undefined,{referenceId:ref.id,status:ref.status,sourceVerified:ref.sourceVerified});return this.safeReference(ref);}
  async requestInfo(actor:number,id:number,dto:ReviewActionDto){const s=await this.full(id);if(![ScreeningStatus.UNDER_REVIEW,ScreeningStatus.READY_FOR_REVIEW].includes(s.status))throw new BadRequestException('Information cannot be requested in the current state.');const before=s.status;s.status=ScreeningStatus.REQUIRES_ATTENTION;s.reviewNotes=dto.reason;s.reviewedByUserId=actor;s.reviewedAt=new Date();await this.screenings.save(s);await this.event(actor,'screening.information_requested',s,{status:before},{status:s.status,reason:dto.reason});return this.view(await this.full(id),true);}
  async complete(actor:number,id:number,dto:ReviewActionDto){const s=await this.full(id);if(s.status!==ScreeningStatus.UNDER_REVIEW)throw new BadRequestException('Screening file is not under review.');const req=this.requirements(s,true);if(req.missing.length)throw new BadRequestException(`Screening cannot be completed: ${req.missing[0]}`);s.status=ScreeningStatus.VETTED;s.reviewNotes=dto.reason;s.reviewedByUserId=actor;s.reviewedAt=new Date();s.vettedAt=new Date();s.retentionReviewAt=new Date(Date.now()+365*86400000);await this.screenings.save(s);await this.event(actor,'screening.vetted',s,{status:ScreeningStatus.UNDER_REVIEW},{status:s.status,vettedAt:s.vettedAt.toISOString()});return this.view(await this.full(id),true);}
  async reject(actor:number,id:number,dto:ReviewActionDto){const s=await this.full(id);if(![ScreeningStatus.UNDER_REVIEW,ScreeningStatus.READY_FOR_REVIEW].includes(s.status))throw new BadRequestException('Screening cannot be rejected in the current state.');const before=s.status;s.status=ScreeningStatus.REJECTED;s.reviewNotes=dto.reason;s.reviewedByUserId=actor;s.reviewedAt=new Date();await this.screenings.save(s);await this.event(actor,'screening.rejected',s,{status:before},{status:s.status,reason:dto.reason});return this.view(await this.full(id),true);}
  async expire(actor:number,id:number,dto:ReviewActionDto){const s=await this.full(id);if(s.status!==ScreeningStatus.VETTED)throw new BadRequestException('Only a VETTED screening file can expire.');s.status=ScreeningStatus.EXPIRED;s.reviewNotes=dto.reason;s.reviewedByUserId=actor;s.reviewedAt=new Date();await this.screenings.save(s);await this.event(actor,'screening.expired',s,{status:ScreeningStatus.VETTED},{status:s.status,reason:dto.reason});return this.view(await this.full(id),true);}
  async isGuardVetted(guardId:number){const s=await this.screenings.findOne({where:{guard:{id:guardId}}});return s?.status===ScreeningStatus.VETTED;}
  async companyOutcome(userId:number,guardId:number){const company=await this.companies.findByUserId(userId);if(!company)throw new NotFoundException('Company not found.');const link=await this.companyGuards.findOne({where:{company:{id:company.id},guard:{id:guardId},status:CompanyGuardStatus.ACTIVE}});if(!link)throw new ForbiddenException('Guard is not linked to this company.');const s=await this.screenings.findOne({where:{guard:{id:guardId}}});return {guardId,status:s?.status??ScreeningStatus.NOT_STARTED,vetted:s?.status===ScreeningStatus.VETTED};}
  private requirements(s:GuardScreening,review=false){
    const chronology=assessContinuousHistory(s.history||[],s.screeningPeriodYears);
    const addressChronology=assessContinuousHistory(s.addresses||[],s.screeningPeriodYears);
    const missing:string[]=[];
    const remediation:Array<{key:string;label:string;status:'COMPLETE'|'ACTION_REQUIRED'|'AWAITING_VERIFICATION'|'VERIFIED';message:string;step:string}>=[];
    const uploadedEvidence=(category:string)=>(s.evidence||[]).filter(e=>String(e.category)===category&&!!e.uploadCompletedAt);
    const add=(key:string,label:string,status:'COMPLETE'|'ACTION_REQUIRED'|'AWAITING_VERIFICATION'|'VERIFIED',message:string,step:string)=>remediation.push({key,label,status,message,step});
    const personalComplete=!!s.legalFullName&&!!s.dateOfBirth&&!!s.nationality;
    if(!personalComplete)missing.push('Personal and identity details are incomplete.');
    add('personal','Personal details',personalComplete?'COMPLETE':'ACTION_REQUIRED',personalComplete?'Information supplied.':'Add your legal name, date of birth and nationality.','personal');
    const currentAddress=(s.addresses||[]).find(a=>a.isCurrent);
    if(!currentAddress)missing.push('Current address history is required.');
    if(!addressChronology.continuous)missing.push('Address history contains an uncovered period.');
    add('address_history','Address history',currentAddress&&addressChronology.continuous?'COMPLETE':'ACTION_REQUIRED',currentAddress&&addressChronology.continuous?'Required address period is covered.':addressChronology.gaps.length?`Add or correct an address covering ${addressChronology.gaps.map(g=>`${g.from}–${g.to}`).join(', ')}.`:'Add your current address.','addresses');
    if(!chronology.continuous)missing.push('Activity history contains an unexplained period.');
    add('activity_history','Activity history',chronology.continuous?'COMPLETE':'ACTION_REQUIRED',chronology.continuous?'Required activity period is covered.':`Add or correct activity covering ${chronology.gaps.map(g=>`${g.from}–${g.to}`).join(', ')}.`,'history');
    const hasReference=(s.references||[]).length>0;
    if(!hasReference)missing.push('At least one linked reference is required.');
    const verifiedReference=(s.references||[]).some(r=>r.status===ReferenceStatus.VERIFIED&&r.sourceVerified);
    add('reference','Reference',!hasReference?'ACTION_REQUIRED':verifiedReference?'VERIFIED':'AWAITING_VERIFICATION',!hasReference?'Add a reference linked to an activity record.':verifiedReference?'A source-verified reference is recorded.':'Reference supplied — awaiting authorised verification.','references');
    const hasConsent=(s.consents||[]).some(c=>!c.withdrawnAt);
    if(!hasConsent)missing.push('Current screening consent is required.');
    add('consent','Consent & declaration',hasConsent?'COMPLETE':'ACTION_REQUIRED',hasConsent?'Current consent recorded.':'Review and accept the screening declaration.','consent');
    const evidenceRequirement=(category:string,label:string,step:string)=>{const records=uploadedEvidence(category);const verified=records.some(e=>e.verificationState===VerificationState.VERIFIED);const latest=[...records].sort((a,b)=>b.id-a.id)[0];const rejected=!verified&&latest?.verificationState===VerificationState.REJECTED;if(!records.length)missing.push(`${label} is required.`);const addressLabel=currentAddress?.address?.replace(/\s+/g,' ')||'your current address';const contextualMissing=category==='address'&&currentAddress?`Upload proof of address for ${addressLabel} covering from ${currentAddress.startDate}${currentAddress.endDate?` to ${currentAddress.endDate}`:' to present'}.`:`Upload ${label.toLowerCase()}.`;add(`${category}_evidence`,label,!records.length||rejected?'ACTION_REQUIRED':verified?'VERIFIED':'AWAITING_VERIFICATION',!records.length?contextualMissing:rejected?`${label} requires correction or replacement.`:verified?`${label} has been verified.`:`${label} uploaded — awaiting authorised verification.`,step);};
    evidenceRequirement('identity','Identity evidence','identity');
    evidenceRequirement('address','Address evidence','addresses');
    evidenceRequirement('sia','SIA evidence','checks');
    evidenceRequirement('right_to_work','Right to Work evidence','checks');
    add('sia_expiry','SIA licence expiry',s.guard?.siaExpiryDate?'COMPLETE':'ACTION_REQUIRED',s.guard?.siaExpiryDate?'SIA licence expiry date supplied.':'Add your SIA licence expiry date.','checks');
    add('rtw_status','Right to Work information',s.guard?.rightToWorkStatus?'COMPLETE':'ACTION_REQUIRED',s.guard?.rightToWorkStatus?'Right to Work information supplied.':'Add your Right to Work status and expiry where applicable.','checks');
    add('identity_check','Identity check',s.identityVerification===VerificationState.VERIFIED?'VERIFIED':s.identityVerification===VerificationState.REJECTED?'ACTION_REQUIRED':'AWAITING_VERIFICATION',s.identityVerification===VerificationState.VERIFIED?'Identity verified.':s.identityVerification===VerificationState.REJECTED?'Identity check requires correction.':'Awaiting authorised identity review.','identity');
    add('sia_check','SIA register check',s.siaRegisterVerification===VerificationState.VERIFIED?'VERIFIED':s.siaRegisterVerification===VerificationState.REJECTED?'ACTION_REQUIRED':'AWAITING_VERIFICATION',s.siaRegisterVerification===VerificationState.VERIFIED?'SIA register check verified.':s.siaRegisterVerification===VerificationState.REJECTED?'SIA check requires correction.':'Awaiting authorised SIA review.','checks');
    add('rtw_check','Right to Work check',s.rightToWorkVerification===VerificationState.VERIFIED?'VERIFIED':s.rightToWorkVerification===VerificationState.REJECTED?'ACTION_REQUIRED':'AWAITING_VERIFICATION',s.rightToWorkVerification===VerificationState.VERIFIED?'Right to Work verified.':s.rightToWorkVerification===VerificationState.REJECTED?'Right to Work check requires correction.':'Awaiting authorised Right to Work review.','checks');
    if((s.exceptions||[]).some(e=>!e.resolved))missing.push('Screening exceptions must be resolved.');
    if(review){if(s.identityVerification!==VerificationState.VERIFIED)missing.push('Identity verification is incomplete.');if(!currentAddress||currentAddress.verificationState!==VerificationState.VERIFIED)missing.push('Current address verification is incomplete.');if(s.siaRegisterVerification!==VerificationState.VERIFIED)missing.push('SIA register verification is incomplete.');if(s.rightToWorkVerification!==VerificationState.VERIFIED)missing.push('Right to Work verification is incomplete.');if(!verifiedReference)missing.push('A source-verified reference is required.');}
    return {missing,chronology,addressChronology,remediation};
  }
  private view(s:GuardScreening,reviewer=false){const req=this.requirements(s);const uploaded=new Set<string>((s.evidence||[]).filter(e=>e.uploadCompletedAt).map(e=>String(e.category)));const candidateCriteria=[!!s.legalFullName&&!!s.dateOfBirth&&!!s.nationality,(s.addresses||[]).some(a=>a.isCurrent)&&!!req.addressChronology.continuous,!!req.chronology.continuous,(s.references||[]).length>0,(s.consents||[]).some(c=>!c.withdrawnAt),uploaded.has('identity'),uploaded.has('address'),uploaded.has('sia'),uploaded.has('right_to_work')];const progress=Math.round(candidateCriteria.filter(Boolean).length/candidateCriteria.length*100);const safeEvidence=(s.evidence||[]).map(e=>({id:e.id,category:e.category,mimeType:e.mimeType,sizeBytes:Number(e.sizeBytes),uploadCompleted:!!e.uploadCompletedAt,verificationState:e.verificationState}));return {...s,evidence:safeEvidence,reviewNotes:reviewer?s.reviewNotes:undefined,requirements:req,progress};}
  private safeReference(ref:ScreeningReference){return {id:ref.id,historyId:ref.history?.id,organisation:ref.organisation,contactPerson:ref.contactPerson,relationship:ref.relationship,businessEmail:ref.businessEmail,phone:ref.phone,postalDetails:ref.postalDetails,status:ref.status,requestedAt:ref.requestedAt,receivedAt:ref.receivedAt,verificationMethod:ref.verificationMethod,sourceVerified:ref.sourceVerified,verifiedAt:ref.verifiedAt};}
}
